package webhooks_test

import (
	"context"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"testing"
	"time"

	"github.com/RRussell11/AIISTECH-Backend/internal/storage"
	"github.com/RRussell11/AIISTECH-Backend/internal/webhooks"
)

// openTestStore opens (or creates) a temporary bbolt database for testing
// and registers cleanup to close it after the test.
func openTestStore(t *testing.T) storage.Store {
	t.Helper()
	dir := t.TempDir()
	s, err := storage.Open(filepath.Join(dir, "test.db"))
	if err != nil {
		t.Fatalf("storage.Open: %v", err)
	}
	t.Cleanup(func() { _ = s.Close() })
	return s
}

func newTestSubscription(id, service, url string, events []string) webhooks.Subscription {
	return webhooks.Subscription{
		ID:        id,
		Service:   service,
		URL:       url,
		Enabled:   true,
		Events:    events,
		CreatedAt: time.Now().UTC().Truncate(time.Second),
		UpdatedAt: time.Now().UTC().Truncate(time.Second),
	}
}

func TestStoreProvider_CreateAndGet(t *testing.T) {
	p := webhooks.NewStoreProvider(openTestStore(t))

	sub := newTestSubscription("sub-1", "svc", "https://example.com/hook", []string{"audit.write"})
	if err := p.Create(&sub); err != nil {
		t.Fatalf("Create() error = %v", err)
	}

	got, err := p.Get(sub.ID)
	if err != nil {
		t.Fatalf("Get() error = %v", err)
	}
	if got.ID != sub.ID {
		t.Errorf("Get() ID = %q, want %q", got.ID, sub.ID)
	}
	if got.URL != sub.URL {
		t.Errorf("Get() URL = %q, want %q", got.URL, sub.URL)
	}
}

func TestStoreProvider_Create_EmptyIDAutoGenerated(t *testing.T) {
	p := webhooks.NewStoreProvider(openTestStore(t))
	sub := newTestSubscription("", "svc", "https://example.com/hook", nil)
	if err := p.Create(&sub); err != nil {
		t.Fatalf("Create() with empty ID: expected no error, got %v", err)
	}
	subs, err := p.ListSubscriptions(context.Background(), "svc", "", "")
	if err != nil {
		t.Fatalf("ListSubscriptions: %v", err)
	}
	if len(subs) != 1 {
		t.Fatalf("want 1 sub after Create, got %d", len(subs))
	}
	if subs[0].ID == "" {
		t.Error("auto-generated ID should be non-empty")
	}
}

func TestStoreProvider_Delete(t *testing.T) {
	p := webhooks.NewStoreProvider(openTestStore(t))
	sub := newTestSubscription("sub-del", "svc", "https://example.com/hook", nil)
	if err := p.Create(&sub); err != nil {
		t.Fatalf("Create() error = %v", err)
	}

	if err := p.Delete(sub.ID); err != nil {
		t.Fatalf("Delete() error = %v", err)
	}

	_, err := p.Get(sub.ID)
	if !errors.Is(err, storage.ErrNotFound) {
		t.Errorf("Get() after Delete: want ErrNotFound, got %v", err)
	}
}

func TestStoreProvider_Delete_NotFound(t *testing.T) {
	p := webhooks.NewStoreProvider(openTestStore(t))
	if err := p.Delete("nonexistent"); !errors.Is(err, storage.ErrNotFound) {
		t.Errorf("Delete() nonexistent: want ErrNotFound, got %v", err)
	}
}

func TestStoreProvider_ListSubscriptions_ServiceFilter(t *testing.T) {
	p := webhooks.NewStoreProvider(openTestStore(t))

	s1 := newTestSubscription("s1", "svc-a", "https://a.example.com/hook", nil)
	s2 := newTestSubscription("s2", "svc-b", "https://b.example.com/hook", nil)
	_ = p.Create(&s1)
	_ = p.Create(&s2)

	subs, err := p.ListSubscriptions(context.Background(), "svc-a", "", "")
	if err != nil {
		t.Fatalf("ListSubscriptions() error = %v", err)
	}
	if len(subs) != 1 {
		t.Fatalf("ListSubscriptions() returned %d subs, want 1", len(subs))
	}
	if subs[0].ID != "s1" {
		t.Errorf("ListSubscriptions() ID = %q, want %q", subs[0].ID, "s1")
	}
}

func TestStoreProvider_ListSubscriptions_NoFilter(t *testing.T) {
	p := webhooks.NewStoreProvider(openTestStore(t))

	s1 := newTestSubscription("s1", "svc-a", "https://a.example.com/hook", nil)
	s2 := newTestSubscription("s2", "svc-b", "https://b.example.com/hook", nil)
	_ = p.Create(&s1)
	_ = p.Create(&s2)

	subs, err := p.ListSubscriptions(context.Background(), "", "", "")
	if err != nil {
		t.Fatalf("ListSubscriptions() error = %v", err)
	}
	if len(subs) != 2 {
		t.Errorf("ListSubscriptions() returned %d subs, want 2", len(subs))
	}
}

func TestStoreProvider_ListSubscriptions_TenantFilter(t *testing.T) {
	p := webhooks.NewStoreProvider(openTestStore(t))

	s1 := newTestSubscription("s1", "svc", "https://a.example.com/hook", nil)
	s1.TenantID = "tenant-x"
	s2 := newTestSubscription("s2", "svc", "https://b.example.com/hook", nil)
	s2.TenantID = "tenant-y"
	_ = p.Create(&s1)
	_ = p.Create(&s2)

	subs, err := p.ListSubscriptions(context.Background(), "svc", "", "tenant-x")
	if err != nil {
		t.Fatalf("ListSubscriptions() error = %v", err)
	}
	if len(subs) != 1 || subs[0].ID != "s1" {
		t.Errorf("ListSubscriptions() tenantID filter: got %v, want [s1]", subs)
	}
}

func TestStoreProvider_ListSubscriptions_Empty(t *testing.T) {
	p := webhooks.NewStoreProvider(openTestStore(t))
	subs, err := p.ListSubscriptions(context.Background(), "svc", "", "")
	if err != nil {
		t.Fatalf("ListSubscriptions() error = %v", err)
	}
	if len(subs) != 0 {
		t.Errorf("ListSubscriptions() on empty store: got %d subs, want 0", len(subs))
	}
}

func TestStoreProvider_ListSubscriptions_TempFile(t *testing.T) {
	// Ensure the store works with a tmp file path and cleans up properly.
	f, err := os.CreateTemp(t.TempDir(), "*.db")
	if err != nil {
		t.Fatal(err)
	}
	_ = f.Close()
	_ = os.Remove(f.Name()) // bbolt will recreate it

	s, err := storage.Open(f.Name())
	if err != nil {
		t.Fatalf("storage.Open: %v", err)
	}
	defer s.Close()

	p := webhooks.NewStoreProvider(s)
	sx := newTestSubscription("x", "svc", "https://x.example.com/hook", nil)
	_ = p.Create(&sx)

	subs, err := p.ListSubscriptions(context.Background(), "svc", "", "")
	if err != nil {
		t.Fatalf("ListSubscriptions: %v", err)
	}
	if len(subs) != 1 {
		t.Errorf("want 1 sub, got %d", len(subs))
	}
}

// --- Update tests ---

func TestStoreProvider_Update_URL(t *testing.T) {
	p := webhooks.NewStoreProvider(openTestStore(t))
	sub := newTestSubscription("sub-upd", "svc", "https://old.example.com/hook", []string{"audit.write"})
	if err := p.Create(&sub); err != nil {
		t.Fatalf("Create: %v", err)
	}

	newURL := "https://new.example.com/hook"
	updated, err := p.Update(sub.ID, webhooks.SubscriptionPatch{URL: &newURL})
	if err != nil {
		t.Fatalf("Update: %v", err)
	}
	if updated.URL != newURL {
		t.Errorf("Update URL = %q, want %q", updated.URL, newURL)
	}
	if updated.ID != sub.ID {
		t.Errorf("Update changed ID from %q to %q", sub.ID, updated.ID)
	}
	if updated.CreatedAt != sub.CreatedAt {
		t.Errorf("Update changed CreatedAt")
	}
	// Verify persisted.
	got, _ := p.Get(sub.ID)
	if got.URL != newURL {
		t.Errorf("persisted URL = %q, want %q", got.URL, newURL)
	}
}

func TestStoreProvider_Update_Enabled(t *testing.T) {
	p := webhooks.NewStoreProvider(openTestStore(t))
	sub := newTestSubscription("sub-en", "svc", "https://example.com/hook", nil)
	sub.Enabled = true
	_ = p.Create(&sub)

	disabled := false
	updated, err := p.Update(sub.ID, webhooks.SubscriptionPatch{Enabled: &disabled})
	if err != nil {
		t.Fatalf("Update: %v", err)
	}
	if updated.Enabled {
		t.Error("expected Enabled=false after Update")
	}
}

func TestStoreProvider_Update_Events_Replace(t *testing.T) {
	p := webhooks.NewStoreProvider(openTestStore(t))
	sub := newTestSubscription("sub-ev", "svc", "https://example.com/hook", []string{"audit.write"})
	_ = p.Create(&sub)

	// PATCH with explicit events list.
	patch := webhooks.SubscriptionPatch{}
	patch.SetEvents([]string{"event.a", "event.b"})
	updated, err := p.Update(sub.ID, patch)
	if err != nil {
		t.Fatalf("Update: %v", err)
	}
	if len(updated.Events) != 2 || updated.Events[0] != "event.a" {
		t.Errorf("Update events = %v, want [event.a event.b]", updated.Events)
	}
}

func TestStoreProvider_Update_Events_Empty_Replaces(t *testing.T) {
	p := webhooks.NewStoreProvider(openTestStore(t))
	sub := newTestSubscription("sub-ev2", "svc", "https://example.com/hook", []string{"audit.write"})
	_ = p.Create(&sub)

	// PATCH with explicit empty events = wildcard / catch-all.
	patch := webhooks.SubscriptionPatch{}
	patch.SetEvents([]string{})
	updated, err := p.Update(sub.ID, patch)
	if err != nil {
		t.Fatalf("Update: %v", err)
	}
	if len(updated.Events) != 0 {
		t.Errorf("Update events = %v, want []", updated.Events)
	}
}

func TestStoreProvider_Update_Events_NilKeeps(t *testing.T) {
	p := webhooks.NewStoreProvider(openTestStore(t))
	sub := newTestSubscription("sub-ev3", "svc", "https://example.com/hook", []string{"audit.write"})
	_ = p.Create(&sub)

	// PATCH without setting events field — existing events should be preserved.
	newURL := "https://changed.example.com/hook"
	updated, err := p.Update(sub.ID, webhooks.SubscriptionPatch{URL: &newURL})
	if err != nil {
		t.Fatalf("Update: %v", err)
	}
	if len(updated.Events) != 1 || updated.Events[0] != "audit.write" {
		t.Errorf("Update events = %v, want [audit.write]", updated.Events)
	}
}

func TestStoreProvider_Update_NotFound(t *testing.T) {
	p := webhooks.NewStoreProvider(openTestStore(t))
	_, err := p.Update("nonexistent", webhooks.SubscriptionPatch{})
	if !errors.Is(err, storage.ErrNotFound) {
		t.Errorf("Update nonexistent: want ErrNotFound, got %v", err)
	}
}

func TestStoreProvider_Update_UpdatedAt_Changes(t *testing.T) {
	p := webhooks.NewStoreProvider(openTestStore(t))
	sub := newTestSubscription("sub-ts", "svc", "https://example.com/hook", nil)
	sub.UpdatedAt = time.Now().UTC().Add(-1 * time.Hour)
	_ = p.Create(&sub)

	before := sub.UpdatedAt
	newURL := "https://new.example.com"
	updated, _ := p.Update(sub.ID, webhooks.SubscriptionPatch{URL: &newURL})
	if !updated.UpdatedAt.After(before) {
		t.Errorf("UpdatedAt was not bumped: before=%v, after=%v", before, updated.UpdatedAt)
	}
}

// --- ListPage tests ---

func TestStoreProvider_ListPage(t *testing.T) {
	p := webhooks.NewStoreProvider(openTestStore(t))

	for i := range 5 {
		sub := newTestSubscription(fmt.Sprintf("sub-page-%02d", i), "svc", "https://example.com/hook", nil)
		if err := p.Create(&sub); err != nil {
			t.Fatalf("Create: %v", err)
		}
	}

	page1, cursor, err := p.ListPage("", 3)
	if err != nil {
		t.Fatalf("ListPage(page1): %v", err)
	}
	if len(page1) != 3 {
		t.Errorf("page1 = %d records, want 3", len(page1))
	}
	if cursor == "" {
		t.Error("expected non-empty cursor after first page")
	}

	page2, cursor2, err := p.ListPage(cursor, 3)
	if err != nil {
		t.Fatalf("ListPage(page2): %v", err)
	}
	if len(page2) != 2 {
		t.Errorf("page2 = %d records, want 2", len(page2))
	}
	if cursor2 != "" {
		t.Errorf("expected empty cursor after last page, got %q", cursor2)
	}
}

func TestStoreProvider_ListPage_Empty(t *testing.T) {
	p := webhooks.NewStoreProvider(openTestStore(t))
	page, cursor, err := p.ListPage("", 10)
	if err != nil {
		t.Fatalf("ListPage empty: %v", err)
	}
	if len(page) != 0 {
		t.Errorf("ListPage empty: got %d records, want 0", len(page))
	}
	if cursor != "" {
		t.Errorf("ListPage empty: cursor = %q, want empty", cursor)
	}
}
